name: hello-world
on: push

env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down
        uses: actions/checkout@v2
      - name: Build app
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload compiled code
        uses: actions/upload-artifact@v2
        with:
          name: compiled-code
          path: app/build/libs/app-0.1-all.jar

  docker-image:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      packages: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GIT_COMMIT }}
      - name: Download compiled code
        uses: actions/download-artifact@v2
        with:
          name: compiled-code
          path: app/build/libs/
      - name: Build Docker image
        run: ci/build-docker.sh
        env:
          DOCKER_USERNAME: ${{ env.docker_username }}
          DOCKER_PASSWORD: ${{ env.docker_password }}
          GIT_COMMIT: ${{ env.GIT_COMMIT }}
